/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicinterpreter;

import java.awt.CardLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MidiUnavailableException;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Admin
 */
public class MusicInterpreter extends javax.swing.JFrame {
    private Musica novaMusica;
    /**
     * Creates new form TelaInterface
     */
    public MusicInterpreter() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/iconeMcCree.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        PainelAbertura = new javax.swing.JPanel();
        botaoIniciar = new javax.swing.JButton();
        fundoAbertura = new javax.swing.JLabel();
        PainelInicial = new javax.swing.JPanel();
        fundoInicial = new javax.swing.JLabel();
        botaoInicialEntrada = new javax.swing.JButton();
        botaoInicialAjuda = new javax.swing.JButton();
        botaoInicialConfiguracoes = new javax.swing.JButton();
        botaoInicialAvancar = new javax.swing.JButton();
        PainelConfiguracoes = new javax.swing.JPanel();
        controleVolume = new javax.swing.JSlider();
        controleInstrumento = new javax.swing.JComboBox<>();
        controleRitmo = new javax.swing.JComboBox<>();
        controleOitava = new javax.swing.JComboBox<>();
        fundoConfiguracoes = new javax.swing.JLabel();
        botaoConfiguracoesVoltar = new javax.swing.JButton();
        PainelTocador = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoTocador = new javax.swing.JTextArea();
        nomeArquivo = new javax.swing.JLabel();
        fundoTocador = new javax.swing.JLabel();
        botaoTocadorVoltar = new javax.swing.JButton();
        botaoTocadorSalvar = new javax.swing.JButton();
        botaoTocadorStop = new javax.swing.JButton();
        botaoTocadorPause = new javax.swing.JButton();
        botaoTocadorPlay = new javax.swing.JButton();
        PainelEdicao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoEdicao = new javax.swing.JTextArea();
        fundoEdicao = new javax.swing.JLabel();
        botaoEdicaoVoltar = new javax.swing.JButton();
        botaoEdicaoSalvar = new javax.swing.JButton();
        PainelAjuda = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoAjuda = new javax.swing.JTextArea();
        EasterEgg = new javax.swing.JLabel();
        fundoAjuda = new javax.swing.JLabel();
        botaoAjudaVoltar = new javax.swing.JButton();
        botaoEasterEgg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saloon Music Player");
        setName("FramePrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 797));
        setResizable(false);

        PainelPrincipal.setLayout(new java.awt.CardLayout());

        PainelAbertura.setLayout(null);

        botaoIniciar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        botaoIniciar.setToolTipText("Pressione para continuar...");
        botaoIniciar.setBorder(null);
        botaoIniciar.setBorderPainted(false);
        botaoIniciar.setContentAreaFilled(false);
        botaoIniciar.setFocusable(false);
        botaoIniciar.setRequestFocusEnabled(false);
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });
        PainelAbertura.add(botaoIniciar);
        botaoIniciar.setBounds(180, 60, 670, 520);

        fundoAbertura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telastartup.png"))); // NOI18N
        PainelAbertura.add(fundoAbertura);
        fundoAbertura.setBounds(0, 0, 1024, 768);

        PainelPrincipal.add(PainelAbertura, "cartaoAbertura");

        PainelInicial.setLayout(null);

        fundoInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fundoInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telainicialsla.png"))); // NOI18N
        PainelInicial.add(fundoInicial);
        fundoInicial.setBounds(0, 0, 1024, 768);

        botaoInicialEntrada.setBorder(null);
        botaoInicialEntrada.setBorderPainted(false);
        botaoInicialEntrada.setContentAreaFilled(false);
        botaoInicialEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicialEntradaActionPerformed(evt);
            }
        });
        PainelInicial.add(botaoInicialEntrada);
        botaoInicialEntrada.setBounds(50, 500, 460, 80);

        botaoInicialAjuda.setBorder(null);
        botaoInicialAjuda.setBorderPainted(false);
        botaoInicialAjuda.setContentAreaFilled(false);
        botaoInicialAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicialAjudaActionPerformed(evt);
            }
        });
        PainelInicial.add(botaoInicialAjuda);
        botaoInicialAjuda.setBounds(940, 10, 70, 70);

        botaoInicialConfiguracoes.setBorder(null);
        botaoInicialConfiguracoes.setBorderPainted(false);
        botaoInicialConfiguracoes.setContentAreaFilled(false);
        botaoInicialConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicialConfiguracoesActionPerformed(evt);
            }
        });
        PainelInicial.add(botaoInicialConfiguracoes);
        botaoInicialConfiguracoes.setBounds(50, 660, 460, 70);

        botaoInicialAvancar.setBorder(null);
        botaoInicialAvancar.setBorderPainted(false);
        botaoInicialAvancar.setContentAreaFilled(false);
        botaoInicialAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicialAvancarActionPerformed(evt);
            }
        });
        PainelInicial.add(botaoInicialAvancar);
        botaoInicialAvancar.setBounds(540, 660, 460, 70);

        PainelPrincipal.add(PainelInicial, "cartaoInicial");

        PainelConfiguracoes.setLayout(null);

        controleVolume.setForeground(new java.awt.Color(102, 102, 102));
        controleVolume.setMajorTickSpacing(127);
        controleVolume.setMaximum(127);
        controleVolume.setMinorTickSpacing(10);
        controleVolume.setPaintLabels(true);
        controleVolume.setPaintTicks(true);
        controleVolume.setToolTipText("Volume Maximo = 127");
        controleVolume.setValue(64);
        controleVolume.setFocusable(false);
        controleVolume.setOpaque(false);
        controleVolume.setRequestFocusEnabled(false);
        PainelConfiguracoes.add(controleVolume);
        controleVolume.setBounds(320, 60, 640, 90);

        controleInstrumento.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        controleInstrumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acoustic Grand Piano", "Bright Acoustic Piano", "Electric Grand Piano", "Honkey Tonk Piano", "Electric Piano", "Electric Piano 1", "Electric Piano 2", "Harpischord", "Clavinet", "Celesta", "Glockenspiel", "Music Box", "Vibraphone", "Marimba", "Xylophone", "Tubular Bells", "Dulcimer", "Drawbar Organ", "Percussive Organ", "Rock Organ", "Church Organ", "Reed Organ", "Accordian", "Harmonica", "Tango Accordian", "Nylon String Guitar", "Steel String Guitar", "Electric Jazz Guitar", "Electric Clean Guitar", "Electric Muted Guitar", "Overdriven Guitar", "Distortion Guitar", "Guitar Harmonics", "Acoustic Bass", "Electric Bass Finger", "Electric Bass Pick", "Fretless Bass", "Slap Bass 1", "Slap Bass 2", "Synth Bass 1", "Synth Bass 2", "Violin", "Viola", "Cello", "Contrabass", "Tremolo Strings", "Pizzicato Strings", "Orchestral Strings", "Timpani", "String Ensemble 1", "String Ensemble 2", "Synthstrings 1", "Synthstrings 2", "Choir AAHS", "Voice OOHS", "Synth Voice", "Orchestra Hit", "Trumpet", "Trombone", "Tuba", "Muted Trumpet", "French Horn", "Brass Section", "Synthbrass 1", "Synthbrass 2", "Soprano Sax", "Alto Sax", "Tenor Sax", "Baritone Sax", "Oboe ", "English Horn", "Bassoon", "Clarinet", "Piccolo", "Flute", "Recorder", "Pan Flute", "Blown Bottle", "Skakuhachi", "Whistle ", "Ocarina", "Square", "Sawtooth", "Calliope", "Chiff", "Charang", "Voice", "Fifths", "Basslead", "New Age", "Warm", "Polysynth", "Choir", "Bowed", "Metallic", "Halo", "Sweep", "Rain", "Soundtrack", "Crystal", "Atmosphere", "Brightness", "Goblins", "Echoes", "Sci-Fi", "Sitar", "Banjo", "Shamisen", "Koto", "Kalimba", "Bagpipe", "Fiddle", "Shanai", "Tinkle Bell", "Agogo", "Steel Drums", "Woodblock", "Taiko Drum", "Melodic Tom", "Synth Drum", "Reverse Cymbal", "Guitar Fret Noise", "Breath Noise", "Seashore", "Bird Tweet", "Telephone Ring", "Helicopter", "Applause", "Gunshot" }));
        controleInstrumento.setToolTipText("");
        controleInstrumento.setBorder(null);
        PainelConfiguracoes.add(controleInstrumento);
        controleInstrumento.setBounds(440, 190, 530, 110);

        controleRitmo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        controleRitmo.setMaximumRowCount(6);
        controleRitmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grave (40 BPM)", "Largo (45 BPM)", "Larghetto (50 BPM)", "Lento (55 BPM)", "Adagio (60 BPM)", "Adagietto (65 BPM)", "Andante (70 BPM)", "Andantino (80 BPM)", "Moderato (95 BPM)", "Allegretto (110 BPM)", "Allegro (120 BPM) - default", "Vivace (145 BPM)", "Presto (180 BPM)", "Prestissimo (220 BPM)" }));
        controleRitmo.setSelectedIndex(10);
        PainelConfiguracoes.add(controleRitmo);
        controleRitmo.setBounds(250, 330, 720, 100);

        controleOitava.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        controleOitava.setMaximumRowCount(5);
        controleOitava.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ª", "2ª", "3ª", "4ª", "5ª", "6ª", "7ª", "8ª", "9ª", "10ª" }));
        controleOitava.setSelectedIndex(4);
        PainelConfiguracoes.add(controleOitava);
        controleOitava.setBounds(280, 460, 690, 100);

        fundoConfiguracoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fundoConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/configuracoes.png"))); // NOI18N
        PainelConfiguracoes.add(fundoConfiguracoes);
        fundoConfiguracoes.setBounds(0, 0, 1024, 768);

        botaoConfiguracoesVoltar.setBorder(null);
        botaoConfiguracoesVoltar.setBorderPainted(false);
        botaoConfiguracoesVoltar.setContentAreaFilled(false);
        botaoConfiguracoesVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfiguracoesVoltarActionPerformed(evt);
            }
        });
        PainelConfiguracoes.add(botaoConfiguracoesVoltar);
        botaoConfiguracoesVoltar.setBounds(40, 650, 130, 90);

        PainelPrincipal.add(PainelConfiguracoes, "cartaoConfiguracoes");

        PainelTocador.setLayout(null);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textoTocador.setColumns(20);
        textoTocador.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        textoTocador.setLineWrap(true);
        textoTocador.setRows(5);
        textoTocador.setBorder(null);
        jScrollPane3.setViewportView(textoTocador);

        PainelTocador.add(jScrollPane3);
        jScrollPane3.setBounds(30, 30, 960, 460);

        nomeArquivo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        nomeArquivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PainelTocador.add(nomeArquivo);
        nomeArquivo.setBounds(170, 530, 740, 50);

        fundoTocador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaplay.png"))); // NOI18N
        PainelTocador.add(fundoTocador);
        fundoTocador.setBounds(0, 0, 1024, 768);

        botaoTocadorVoltar.setBorder(null);
        botaoTocadorVoltar.setBorderPainted(false);
        botaoTocadorVoltar.setContentAreaFilled(false);
        botaoTocadorVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTocadorVoltarActionPerformed(evt);
            }
        });
        PainelTocador.add(botaoTocadorVoltar);
        botaoTocadorVoltar.setBounds(20, 520, 120, 80);

        botaoTocadorSalvar.setBorder(null);
        botaoTocadorSalvar.setBorderPainted(false);
        botaoTocadorSalvar.setContentAreaFilled(false);
        botaoTocadorSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTocadorSalvarActionPerformed(evt);
            }
        });
        PainelTocador.add(botaoTocadorSalvar);
        botaoTocadorSalvar.setBounds(920, 520, 70, 80);

        botaoTocadorStop.setBorder(null);
        botaoTocadorStop.setBorderPainted(false);
        botaoTocadorStop.setContentAreaFilled(false);
        botaoTocadorStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTocadorStopActionPerformed(evt);
            }
        });
        PainelTocador.add(botaoTocadorStop);
        botaoTocadorStop.setBounds(150, 630, 130, 130);

        botaoTocadorPause.setBorder(null);
        botaoTocadorPause.setBorderPainted(false);
        botaoTocadorPause.setContentAreaFilled(false);
        botaoTocadorPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTocadorPauseActionPerformed(evt);
            }
        });
        PainelTocador.add(botaoTocadorPause);
        botaoTocadorPause.setBounds(440, 630, 140, 130);

        botaoTocadorPlay.setBorder(null);
        botaoTocadorPlay.setBorderPainted(false);
        botaoTocadorPlay.setContentAreaFilled(false);
        botaoTocadorPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTocadorPlayActionPerformed(evt);
            }
        });
        PainelTocador.add(botaoTocadorPlay);
        botaoTocadorPlay.setBounds(740, 630, 130, 130);

        PainelPrincipal.add(PainelTocador, "cartaoTocador");

        PainelEdicao.setLayout(null);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textoEdicao.setColumns(20);
        textoEdicao.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        textoEdicao.setLineWrap(true);
        textoEdicao.setRows(5);
        textoEdicao.setBorder(null);
        textoEdicao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textoEdicao.setHighlighter(null);
        jScrollPane1.setViewportView(textoEdicao);

        PainelEdicao.add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 970, 570);

        fundoEdicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaedicao.png"))); // NOI18N
        PainelEdicao.add(fundoEdicao);
        fundoEdicao.setBounds(0, 0, 1024, 768);

        botaoEdicaoVoltar.setBorder(null);
        botaoEdicaoVoltar.setBorderPainted(false);
        botaoEdicaoVoltar.setContentAreaFilled(false);
        botaoEdicaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEdicaoVoltarActionPerformed(evt);
            }
        });
        PainelEdicao.add(botaoEdicaoVoltar);
        botaoEdicaoVoltar.setBounds(40, 660, 130, 70);

        botaoEdicaoSalvar.setBorder(null);
        botaoEdicaoSalvar.setBorderPainted(false);
        botaoEdicaoSalvar.setContentAreaFilled(false);
        botaoEdicaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEdicaoSalvarActionPerformed(evt);
            }
        });
        PainelEdicao.add(botaoEdicaoSalvar);
        botaoEdicaoSalvar.setBounds(390, 660, 80, 70);

        PainelPrincipal.add(PainelEdicao, "cartaoEdicao");

        PainelAjuda.setLayout(null);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textoAjuda.setEditable(false);
        textoAjuda.setColumns(20);
        textoAjuda.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        textoAjuda.setLineWrap(true);
        textoAjuda.setRows(5);
        textoAjuda.setBorder(null);
        jScrollPane2.setViewportView(textoAjuda);

        PainelAjuda.add(jScrollPane2);
        jScrollPane2.setBounds(30, 20, 970, 570);

        EasterEgg.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        EasterEgg.setForeground(new java.awt.Color(255, 255, 153));
        EasterEgg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EasterEgg.setText("MIM");
        PainelAjuda.add(EasterEgg);
        EasterEgg.setBounds(560, 650, 190, 80);

        fundoAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaajuda.png"))); // NOI18N
        PainelAjuda.add(fundoAjuda);
        fundoAjuda.setBounds(0, 0, 1024, 768);

        botaoAjudaVoltar.setBorder(null);
        botaoAjudaVoltar.setBorderPainted(false);
        botaoAjudaVoltar.setContentAreaFilled(false);
        botaoAjudaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAjudaVoltarActionPerformed(evt);
            }
        });
        PainelAjuda.add(botaoAjudaVoltar);
        botaoAjudaVoltar.setBounds(40, 660, 130, 70);

        botaoEasterEgg.setBorder(null);
        botaoEasterEgg.setBorderPainted(false);
        botaoEasterEgg.setContentAreaFilled(false);
        botaoEasterEgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEasterEggActionPerformed(evt);
            }
        });
        PainelAjuda.add(botaoEasterEgg);
        botaoEasterEgg.setBounds(83, 620, 40, 0);

        PainelPrincipal.add(PainelAjuda, "cartaoAjuda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInicialAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicialAvancarActionPerformed
        if (textoEdicao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione uma entrada!");
        } 
        else{
            novaMusica = new Musica(textoEdicao.getText(), controleVolume.getValue(), controleInstrumento.getSelectedIndex(), controleRitmo.getSelectedIndex(), controleOitava.getSelectedIndex());
            textoTocador.setText(novaMusica.pegaNotas());
            textoTocador.setCaretPosition(0);
            
            CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
            cartao.show(PainelPrincipal, "cartaoTocador");
        }
    }//GEN-LAST:event_botaoInicialAvancarActionPerformed

    private void botaoInicialAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicialAjudaActionPerformed
        String ajudatxt = ManipuladorArquivo.leArquivo("ajuda.txt");
        textoAjuda.setText(ajudatxt);
        textoAjuda.setCaretPosition(0);  // colocar scroll no topo
        EasterEgg.setVisible(false);  
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoAjuda");
    }//GEN-LAST:event_botaoInicialAjudaActionPerformed

    private void botaoInicialConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicialConfiguracoesActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoConfiguracoes");
    }//GEN-LAST:event_botaoInicialConfiguracoesActionPerformed

    private void botaoConfiguracoesVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfiguracoesVoltarActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoInicial");
    }//GEN-LAST:event_botaoConfiguracoesVoltarActionPerformed

    private void botaoTocadorVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTocadorVoltarActionPerformed
        novaMusica.fechaMusica();
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoInicial");
    }//GEN-LAST:event_botaoTocadorVoltarActionPerformed

    private void botaoEdicaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEdicaoVoltarActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoInicial");
    }//GEN-LAST:event_botaoEdicaoVoltarActionPerformed

    private void botaoAjudaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAjudaVoltarActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoInicial");
    }//GEN-LAST:event_botaoAjudaVoltarActionPerformed

    private void botaoInicialEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicialEntradaActionPerformed
        Object[] opcoesTexto = { "Arquivo", "Texto" };
        Integer opcaoEntrada = JOptionPane.showOptionDialog(this,"Selecione o modo de entrada:","Entrada",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opcoesTexto,opcoesTexto[0]);
        if (opcaoEntrada == 0){ // escolher a primeira opçao, ou seja "Arquivo"
            JFileChooser seletorArquivo = new JFileChooser(System.getProperty("user.home") + "/Desktop");             
            seletorArquivo.addChoosableFileFilter(new FileNameExtensionFilter("Arquivo de Texto","txt"));
            seletorArquivo.setAcceptAllFileFilterUsed(false);                      
            int foiSelecionado = seletorArquivo.showOpenDialog(this);
            if(foiSelecionado == JFileChooser.APPROVE_OPTION){
                File arquivoEntrada = seletorArquivo.getSelectedFile();
                String caminhoArquivo = arquivoEntrada.getAbsolutePath();
                nomeArquivo.setText(arquivoEntrada.getName());

                String entradaLida = ManipuladorArquivo.leArquivo(caminhoArquivo);
                textoEdicao.setText(entradaLida);
                textoEdicao.setCaretPosition(0);
                CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
                cartao.show(PainelPrincipal, "cartaoEdicao");
            }
        }
            
        else if (opcaoEntrada == 1){ // escolher a segunda opcao, ou seja "Texto"
            textoEdicao.setText("");
            textoEdicao.setCaretPosition(0);
            nomeArquivo.setText("Entrada de Texto");
            CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
            cartao.show(PainelPrincipal, "cartaoEdicao");
        }
       
    }//GEN-LAST:event_botaoInicialEntradaActionPerformed

    private void botaoEasterEggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEasterEggActionPerformed
         EasterEgg.setVisible(true);
    }//GEN-LAST:event_botaoEasterEggActionPerformed

    private void botaoEdicaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEdicaoSalvarActionPerformed
        JFileChooser seletorArquivo = new JFileChooser(System.getProperty("user.home") + "/Desktop");
        seletorArquivo.addChoosableFileFilter(new FileNameExtensionFilter("Arquivo de Texto","txt"));
        seletorArquivo.setAcceptAllFileFilterUsed(false);
        int foiSelecionado = seletorArquivo.showSaveDialog(this);
        if(foiSelecionado == JFileChooser.APPROVE_OPTION){
            File arquivoEntrada = seletorArquivo.getSelectedFile();
            String caminhoArquivo = arquivoEntrada.getAbsolutePath();
            String nome = arquivoEntrada.getName();
            
            if(!caminhoArquivo.endsWith(".txt") ){
                caminhoArquivo += ".txt";
                nome += ".txt";
            }
            nomeArquivo.setText(nome);
            ManipuladorArquivo.salvaArquivoTexto(caminhoArquivo, textoEdicao.getText());
        }
    }//GEN-LAST:event_botaoEdicaoSalvarActionPerformed

    private void botaoTocadorPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTocadorPlayActionPerformed
        if(novaMusica.musicaEstaPausada()){
            novaMusica.resumeMusica();
        }
        else{
            try {
                novaMusica.tocaMusica();
            } catch (InvalidMidiDataException ex) {
                Logger.getLogger(MusicInterpreter.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MidiUnavailableException ex) {
                Logger.getLogger(MusicInterpreter.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_botaoTocadorPlayActionPerformed

    private void botaoTocadorPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTocadorPauseActionPerformed
       novaMusica.pausaMusica();
    }//GEN-LAST:event_botaoTocadorPauseActionPerformed

    private void botaoTocadorStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTocadorStopActionPerformed
       novaMusica.paraMusica();
    }//GEN-LAST:event_botaoTocadorStopActionPerformed

    private void botaoTocadorSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTocadorSalvarActionPerformed
        JFileChooser seletorArquivo = new JFileChooser(System.getProperty("user.home") + "/Desktop");
        seletorArquivo.addChoosableFileFilter(new FileNameExtensionFilter("Arquivo de Audio","mid"));
        seletorArquivo.setAcceptAllFileFilterUsed(false);
        int foiSelecionado = seletorArquivo.showSaveDialog(this);
        if(foiSelecionado == JFileChooser.APPROVE_OPTION){
            File arquivoEntrada = seletorArquivo.getSelectedFile();
            String caminhoArquivo = arquivoEntrada.getAbsolutePath();
            
            try {
                if(!caminhoArquivo.endsWith(".mid")){
                caminhoArquivo += ".mid";
            }
                novaMusica.salvaMIDI(caminhoArquivo);
            } catch (IOException ex){
                Logger.getLogger(MusicInterpreter.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botaoTocadorSalvarActionPerformed

    private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoInicial");
    }//GEN-LAST:event_botaoIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {           
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicInterpreter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicInterpreter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicInterpreter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicInterpreter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicInterpreter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EasterEgg;
    private javax.swing.JPanel PainelAbertura;
    private javax.swing.JPanel PainelAjuda;
    private javax.swing.JPanel PainelConfiguracoes;
    private javax.swing.JPanel PainelEdicao;
    private javax.swing.JPanel PainelInicial;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelTocador;
    private javax.swing.JButton botaoAjudaVoltar;
    private javax.swing.JButton botaoConfiguracoesVoltar;
    private javax.swing.JButton botaoEasterEgg;
    private javax.swing.JButton botaoEdicaoSalvar;
    private javax.swing.JButton botaoEdicaoVoltar;
    private javax.swing.JButton botaoInicialAjuda;
    private javax.swing.JButton botaoInicialAvancar;
    private javax.swing.JButton botaoInicialConfiguracoes;
    private javax.swing.JButton botaoInicialEntrada;
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JButton botaoTocadorPause;
    private javax.swing.JButton botaoTocadorPlay;
    private javax.swing.JButton botaoTocadorSalvar;
    private javax.swing.JButton botaoTocadorStop;
    private javax.swing.JButton botaoTocadorVoltar;
    private javax.swing.JComboBox<String> controleInstrumento;
    private javax.swing.JComboBox<String> controleOitava;
    private javax.swing.JComboBox<String> controleRitmo;
    private javax.swing.JSlider controleVolume;
    private javax.swing.JLabel fundoAbertura;
    private javax.swing.JLabel fundoAjuda;
    private javax.swing.JLabel fundoConfiguracoes;
    private javax.swing.JLabel fundoEdicao;
    private javax.swing.JLabel fundoInicial;
    private javax.swing.JLabel fundoTocador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nomeArquivo;
    private javax.swing.JTextArea textoAjuda;
    private javax.swing.JTextArea textoEdicao;
    private javax.swing.JTextArea textoTocador;
    // End of variables declaration//GEN-END:variables
}
