/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicinterpreter;

import java.awt.CardLayout;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MidiUnavailableException;

/**
 *
 * @author Admin
 */
public class TelaInterface extends javax.swing.JFrame {

    /**
     * Creates new form TelaInterface
     */
    public TelaInterface() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/hue.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        PainelInicial = new javax.swing.JPanel();
        fundoInicial = new javax.swing.JLabel();
        botaoInicialEntrada = new javax.swing.JButton();
        botaoInicialAjuda = new javax.swing.JButton();
        botaoInicialConfiguracoes = new javax.swing.JButton();
        botaoInicialAvancar = new javax.swing.JButton();
        PainelConfiguracoes = new javax.swing.JPanel();
        fundoConfiguracoes = new javax.swing.JLabel();
        botaoConfiguracoesVoltar = new javax.swing.JButton();
        PainelTocador = new javax.swing.JPanel();
        fundoTocador = new javax.swing.JLabel();
        botaoTocadorVoltar = new javax.swing.JButton();
        botaoTocadorSalvar = new javax.swing.JButton();
        botaoTocadorStop = new javax.swing.JButton();
        botaoTocadorPause = new javax.swing.JButton();
        botaoTocadorPlay = new javax.swing.JButton();
        PainelEdicao = new javax.swing.JPanel();
        fundoEdicao = new javax.swing.JLabel();
        botaoEdicaoVoltar = new javax.swing.JButton();
        botaoEdicaoSalvar = new javax.swing.JButton();
        PainelAjuda = new javax.swing.JPanel();
        fundoAjuda = new javax.swing.JLabel();
        botaoAjudaVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("FramePrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 797));
        setResizable(false);

        PainelPrincipal.setLayout(new java.awt.CardLayout());

        PainelInicial.setLayout(null);

        fundoInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fundoInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telainicialsla.png"))); // NOI18N
        PainelInicial.add(fundoInicial);
        fundoInicial.setBounds(0, 0, 1024, 768);
        PainelInicial.add(botaoInicialEntrada);
        botaoInicialEntrada.setBounds(50, 500, 460, 80);

        botaoInicialAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicialAjudaActionPerformed(evt);
            }
        });
        PainelInicial.add(botaoInicialAjuda);
        botaoInicialAjuda.setBounds(940, 10, 70, 70);

        botaoInicialConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicialConfiguracoesActionPerformed(evt);
            }
        });
        PainelInicial.add(botaoInicialConfiguracoes);
        botaoInicialConfiguracoes.setBounds(50, 660, 460, 70);

        botaoInicialAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicialAvancarActionPerformed(evt);
            }
        });
        PainelInicial.add(botaoInicialAvancar);
        botaoInicialAvancar.setBounds(540, 660, 460, 70);

        PainelPrincipal.add(PainelInicial, "cartaoInicial");

        PainelConfiguracoes.setLayout(null);

        fundoConfiguracoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fundoConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/configuracoes.png"))); // NOI18N
        PainelConfiguracoes.add(fundoConfiguracoes);
        fundoConfiguracoes.setBounds(0, 0, 1024, 768);

        botaoConfiguracoesVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfiguracoesVoltarActionPerformed(evt);
            }
        });
        PainelConfiguracoes.add(botaoConfiguracoesVoltar);
        botaoConfiguracoesVoltar.setBounds(40, 650, 130, 90);

        PainelPrincipal.add(PainelConfiguracoes, "cartaoConfiguracoes");

        PainelTocador.setLayout(null);

        fundoTocador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaplay.png"))); // NOI18N
        PainelTocador.add(fundoTocador);
        fundoTocador.setBounds(0, 0, 1024, 768);

        botaoTocadorVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTocadorVoltarActionPerformed(evt);
            }
        });
        PainelTocador.add(botaoTocadorVoltar);
        botaoTocadorVoltar.setBounds(20, 520, 120, 80);
        PainelTocador.add(botaoTocadorSalvar);
        botaoTocadorSalvar.setBounds(920, 520, 70, 80);
        PainelTocador.add(botaoTocadorStop);
        botaoTocadorStop.setBounds(150, 630, 130, 130);
        PainelTocador.add(botaoTocadorPause);
        botaoTocadorPause.setBounds(440, 630, 140, 130);
        PainelTocador.add(botaoTocadorPlay);
        botaoTocadorPlay.setBounds(740, 630, 130, 130);

        PainelPrincipal.add(PainelTocador, "cartaoTocador");

        PainelEdicao.setLayout(null);

        fundoEdicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaedicao.png"))); // NOI18N
        PainelEdicao.add(fundoEdicao);
        fundoEdicao.setBounds(0, 0, 1024, 768);

        botaoEdicaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEdicaoVoltarActionPerformed(evt);
            }
        });
        PainelEdicao.add(botaoEdicaoVoltar);
        botaoEdicaoVoltar.setBounds(40, 660, 130, 70);
        PainelEdicao.add(botaoEdicaoSalvar);
        botaoEdicaoSalvar.setBounds(390, 660, 80, 70);

        PainelPrincipal.add(PainelEdicao, "cartaoEdicao");

        PainelAjuda.setLayout(null);

        fundoAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaajuda.png"))); // NOI18N
        PainelAjuda.add(fundoAjuda);
        fundoAjuda.setBounds(0, 0, 1024, 768);

        botaoAjudaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAjudaVoltarActionPerformed(evt);
            }
        });
        PainelAjuda.add(botaoAjudaVoltar);
        botaoAjudaVoltar.setBounds(40, 660, 130, 70);

        PainelPrincipal.add(PainelAjuda, "cartaoAjuda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInicialAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicialAvancarActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoTocador");
    }//GEN-LAST:event_botaoInicialAvancarActionPerformed

    private void botaoInicialAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicialAjudaActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoAjuda");
    }//GEN-LAST:event_botaoInicialAjudaActionPerformed

    private void botaoInicialConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicialConfiguracoesActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoConfiguracoes");
    }//GEN-LAST:event_botaoInicialConfiguracoesActionPerformed

    private void botaoConfiguracoesVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfiguracoesVoltarActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoInicial");
    }//GEN-LAST:event_botaoConfiguracoesVoltarActionPerformed

    private void botaoTocadorVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTocadorVoltarActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoInicial");
    }//GEN-LAST:event_botaoTocadorVoltarActionPerformed

    private void botaoEdicaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEdicaoVoltarActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoInicial");
    }//GEN-LAST:event_botaoEdicaoVoltarActionPerformed

    private void botaoAjudaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAjudaVoltarActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoInicial");
    }//GEN-LAST:event_botaoAjudaVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelAjuda;
    private javax.swing.JPanel PainelConfiguracoes;
    private javax.swing.JPanel PainelEdicao;
    private javax.swing.JPanel PainelInicial;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelTocador;
    private javax.swing.JButton botaoAjudaVoltar;
    private javax.swing.JButton botaoConfiguracoesVoltar;
    private javax.swing.JButton botaoEdicaoSalvar;
    private javax.swing.JButton botaoEdicaoVoltar;
    private javax.swing.JButton botaoInicialAjuda;
    private javax.swing.JButton botaoInicialAvancar;
    private javax.swing.JButton botaoInicialConfiguracoes;
    private javax.swing.JButton botaoInicialEntrada;
    private javax.swing.JButton botaoTocadorPause;
    private javax.swing.JButton botaoTocadorPlay;
    private javax.swing.JButton botaoTocadorSalvar;
    private javax.swing.JButton botaoTocadorStop;
    private javax.swing.JButton botaoTocadorVoltar;
    private javax.swing.JLabel fundoAjuda;
    private javax.swing.JLabel fundoConfiguracoes;
    private javax.swing.JLabel fundoEdicao;
    private javax.swing.JLabel fundoInicial;
    private javax.swing.JLabel fundoTocador;
    // End of variables declaration//GEN-END:variables
}
