/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicinterpreter;

import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MidiUnavailableException;


/**
 *
 * @author Admin
 */
public class TelaInterface extends javax.swing.JFrame {

    /**
     * Creates new form TelaInterface
     */
    public TelaInterface() {
        initComponents();
       //mudar o nome da imagem this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/rocketicon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPai = new javax.swing.JPanel();
        PainelInicial = new javax.swing.JPanel();
        botaoIrConfiguracoes = new javax.swing.JButton();
        botaoIrTocador = new javax.swing.JButton();
        rotulokatiau = new javax.swing.JLabel();
        PainelConfiguracoes = new javax.swing.JPanel();
        botaoVoltarConfiguracoes = new javax.swing.JButton();
        rotulovolume = new javax.swing.JLabel();
        rotuloinstrumento = new javax.swing.JLabel();
        rotulofodase = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        PainelTocador = new javax.swing.JPanel();
        botaoprei = new javax.swing.JButton();
        botaopausi = new javax.swing.JButton();
        botaovoltalogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("FramePrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        PainelPai.setName(""); // NOI18N
        PainelPai.setLayout(new java.awt.CardLayout());

        botaoIrConfiguracoes.setText("Configuracoes");
        botaoIrConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIrConfiguracoesActionPerformed(evt);
            }
        });

        botaoIrTocador.setText("go for it");
        botaoIrTocador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIrTocadorActionPerformed(evt);
            }
        });

        rotulokatiau.setText("katiau");

        javax.swing.GroupLayout PainelInicialLayout = new javax.swing.GroupLayout(PainelInicial);
        PainelInicial.setLayout(PainelInicialLayout);
        PainelInicialLayout.setHorizontalGroup(
            PainelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInicialLayout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(rotulokatiau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PainelInicialLayout.createSequentialGroup()
                .addComponent(botaoIrConfiguracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(529, 529, 529)
                .addComponent(botaoIrTocador, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PainelInicialLayout.setVerticalGroup(
            PainelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInicialLayout.createSequentialGroup()
                .addComponent(rotulokatiau)
                .addGap(309, 309, 309)
                .addGroup(PainelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoIrConfiguracoes)
                    .addComponent(botaoIrTocador)))
        );

        PainelPai.add(PainelInicial, "cartaoInicial");

        botaoVoltarConfiguracoes.setText("voltar pro menu");
        botaoVoltarConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarConfiguracoesActionPerformed(evt);
            }
        });

        rotulovolume.setText("volume");

        rotuloinstrumento.setText("instrumento");

        rotulofodase.setText("fodase");

        javax.swing.GroupLayout PainelConfiguracoesLayout = new javax.swing.GroupLayout(PainelConfiguracoes);
        PainelConfiguracoes.setLayout(PainelConfiguracoesLayout);
        PainelConfiguracoesLayout.setHorizontalGroup(
            PainelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoVoltarConfiguracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(PainelConfiguracoesLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(PainelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelConfiguracoesLayout.createSequentialGroup()
                        .addComponent(rotulovolume)
                        .addGap(166, 166, 166)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rotuloinstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotulofodase, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        PainelConfiguracoesLayout.setVerticalGroup(
            PainelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelConfiguracoesLayout.createSequentialGroup()
                .addGroup(PainelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotulovolume)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(rotuloinstrumento)
                .addGap(47, 47, 47)
                .addComponent(rotulofodase)
                .addGap(309, 309, 309)
                .addComponent(botaoVoltarConfiguracoes))
        );

        PainelPai.add(PainelConfiguracoes, "cartaoConfiguracoes");

        botaoprei.setText("prei");
        botaoprei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaopreiActionPerformed(evt);
            }
        });

        botaopausi.setText("pausi");

        botaovoltalogo.setText("voltalogo");
        botaovoltalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaovoltalogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelTocadorLayout = new javax.swing.GroupLayout(PainelTocador);
        PainelTocador.setLayout(PainelTocadorLayout);
        PainelTocadorLayout.setHorizontalGroup(
            PainelTocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTocadorLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(botaovoltalogo))
            .addGroup(PainelTocadorLayout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(botaoprei)
                .addGap(85, 85, 85)
                .addComponent(botaopausi))
        );
        PainelTocadorLayout.setVerticalGroup(
            PainelTocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTocadorLayout.createSequentialGroup()
                .addGap(540, 540, 540)
                .addComponent(botaovoltalogo)
                .addGap(103, 103, 103)
                .addGroup(PainelTocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoprei)
                    .addComponent(botaopausi)))
        );

        PainelPai.add(PainelTocador, "cartaoTocador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PainelPai.getAccessibleContext().setAccessibleName("PainelPrincipal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIrConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIrConfiguracoesActionPerformed
        CardLayout cartao = (CardLayout) PainelPai.getLayout();
        cartao.show(PainelPai, "cartaoConfiguracoes");
    }//GEN-LAST:event_botaoIrConfiguracoesActionPerformed

    private void botaoIrTocadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIrTocadorActionPerformed
        CardLayout cartao = (CardLayout) PainelPai.getLayout();
        cartao.show(PainelPai, "cartaoTocador");
    }//GEN-LAST:event_botaoIrTocadorActionPerformed

    private void botaoVoltarConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarConfiguracoesActionPerformed
        CardLayout cartao = (CardLayout) PainelPai.getLayout();
        cartao.show(PainelPai, "cartaoInicial");
    }//GEN-LAST:event_botaoVoltarConfiguracoesActionPerformed

    private void botaovoltalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaovoltalogoActionPerformed
        CardLayout cartao = (CardLayout) PainelPai.getLayout();
        cartao.show(PainelPai, "cartaoInicial");
    }//GEN-LAST:event_botaovoltalogoActionPerformed

    private void botaopreiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaopreiActionPerformed
        String entradaLida = LeitorArquivo.leArquivo("arquivoKatiau.txt");
        Musica novaMusica = new Musica(entradaLida);
        try {
            novaMusica.tocaMusica();
        } catch (InvalidMidiDataException ex) {
            Logger.getLogger(TelaInterface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MidiUnavailableException ex) {
            Logger.getLogger(TelaInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaopreiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelConfiguracoes;
    private javax.swing.JPanel PainelInicial;
    private javax.swing.JPanel PainelPai;
    private javax.swing.JPanel PainelTocador;
    private javax.swing.JButton botaoIrConfiguracoes;
    private javax.swing.JButton botaoIrTocador;
    private javax.swing.JButton botaoVoltarConfiguracoes;
    private javax.swing.JButton botaopausi;
    private javax.swing.JButton botaoprei;
    private javax.swing.JButton botaovoltalogo;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel rotulofodase;
    private javax.swing.JLabel rotuloinstrumento;
    private javax.swing.JLabel rotulokatiau;
    private javax.swing.JLabel rotulovolume;
    // End of variables declaration//GEN-END:variables
}
