/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicinterpreter;

import java.awt.CardLayout;
import java.awt.Toolkit;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MidiUnavailableException;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class TelaInterface extends javax.swing.JFrame {
    private Musica novaMusica;
    /**
     * Creates new form TelaInterface
     */
    public TelaInterface() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/iconeMcCree.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        PainelInicial = new javax.swing.JPanel();
        fundoInicial = new javax.swing.JLabel();
        botaoInicialEntrada = new javax.swing.JButton();
        botaoInicialAjuda = new javax.swing.JButton();
        botaoInicialConfiguracoes = new javax.swing.JButton();
        botaoInicialAvancar = new javax.swing.JButton();
        PainelConfiguracoes = new javax.swing.JPanel();
        controleVolume = new javax.swing.JSlider();
        controleInstrumento = new javax.swing.JComboBox<>();
        fundoConfiguracoes = new javax.swing.JLabel();
        botaoConfiguracoesVoltar = new javax.swing.JButton();
        PainelTocador = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoTocador = new javax.swing.JTextArea();
        nomeArquivo = new javax.swing.JLabel();
        fundoTocador = new javax.swing.JLabel();
        botaoTocadorVoltar = new javax.swing.JButton();
        botaoTocadorSalvar = new javax.swing.JButton();
        botaoTocadorStop = new javax.swing.JButton();
        botaoTocadorPause = new javax.swing.JButton();
        botaoTocadorPlay = new javax.swing.JButton();
        PainelEdicao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoEdicao = new javax.swing.JTextArea();
        fundoEdicao = new javax.swing.JLabel();
        botaoEdicaoVoltar = new javax.swing.JButton();
        botaoEdicaoSalvar = new javax.swing.JButton();
        PainelAjuda = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoAjuda = new javax.swing.JTextArea();
        EasterEgg = new javax.swing.JLabel();
        fundoAjuda = new javax.swing.JLabel();
        botaoAjudaVoltar = new javax.swing.JButton();
        botaoEasterEgg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saloon Music Player");
        setName("FramePrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 797));
        setResizable(false);

        PainelPrincipal.setLayout(new java.awt.CardLayout());

        PainelInicial.setLayout(null);

        fundoInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fundoInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telainicialsla.png"))); // NOI18N
        PainelInicial.add(fundoInicial);
        fundoInicial.setBounds(0, 0, 1024, 768);

        botaoInicialEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicialEntradaActionPerformed(evt);
            }
        });
        PainelInicial.add(botaoInicialEntrada);
        botaoInicialEntrada.setBounds(50, 500, 460, 80);

        botaoInicialAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicialAjudaActionPerformed(evt);
            }
        });
        PainelInicial.add(botaoInicialAjuda);
        botaoInicialAjuda.setBounds(940, 10, 70, 70);

        botaoInicialConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicialConfiguracoesActionPerformed(evt);
            }
        });
        PainelInicial.add(botaoInicialConfiguracoes);
        botaoInicialConfiguracoes.setBounds(50, 660, 460, 70);

        botaoInicialAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicialAvancarActionPerformed(evt);
            }
        });
        PainelInicial.add(botaoInicialAvancar);
        botaoInicialAvancar.setBounds(540, 660, 460, 70);

        PainelPrincipal.add(PainelInicial, "cartaoInicial");

        PainelConfiguracoes.setLayout(null);

        controleVolume.setMajorTickSpacing(10);
        controleVolume.setMaximum(127);
        controleVolume.setMinorTickSpacing(10);
        controleVolume.setPaintTicks(true);
        controleVolume.setValue(64);
        PainelConfiguracoes.add(controleVolume);
        controleVolume.setBounds(310, 80, 660, 100);

        controleInstrumento.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        controleInstrumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acoustic Grand Piano", "Bright Acoustic Piano", "Electric Grand Piano", "Honkey Tonk Piano", "Electric Piano", "Electric Piano 1", "Electric Piano 2", "Harpischord", "Clavinet", "Celesta", "Glockenspiel", "Music Box", "Vibraphone", "Marimba", "Xylophone", "Tubular Bells", "Dulcimer", "Drawbar Organ", "Percussive Organ", "Rock Organ", "Church Organ", "Reed Organ", "Accordian", "Harmonica", "Tango Accordian", "Nylon String Guitar", "Steel String Guitar", "Electric Jazz Guitar", "Electric Clean Guitar", "Electric Muted Guitar", "Overdriven Guitar", "Distortion Guitar", "Guitar Harmonics", "Acoustic Bass", "Electric Bass Finger", "Electric Bass Pick", "Fretless Bass", "Slap Bass 1", "Slap Bass 2", "Synth Bass 1", "Synth Bass 2", "Violin", "Viola", "Cello", "Contrabass", "Tremolo Strings", "Pizzicato Strings", "Orchestral Strings", "Timpani", "String Ensemble 1", "String Ensemble 2", "Synthstrings 1", "Synthstrings 2", "Choir AAHS", "Voice OOHS", "Synth Voice", "Orchestra Hit", "Trumpet", "Trombone", "Tuba", "Muted Trumpet", "French Horn", "Brass Section", "Synthbrass 1", "Synthbrass 2", "Soprano Sax", "Alto Sax", "Tenor Sax", "Baritone Sax", "Oboe ", "English Horn", "Bassoon", "Clarinet", "Piccolo", "Flute", "Recorder", "Pan Flute", "Blown Bottle", "Skakuhachi", "Whistle ", "Ocarina", "Square", "Sawtooth", "Calliope", "Chiff", "Charang", "Voice", "Fifths", "Basslead", "New Age", "Warm", "Polysynth", "Choir", "Bowed", "Metallic", "Halo", "Sweep", "Rain", "Soundtrack", "Crystal", "Atmosphere", "Brightness", "Goblins", "Echoes", "Sci-Fi", "Sitar", "Banjo", "Shamisen", "Koto", "Kalimba", "Bagpipe", "Fiddle", "Shanai", "Tinkle Bell", "Agogo", "Steel Drums", "Woodblock", "Taiko Drum", "Melodic Tom", "Synth Drum", "Reverse Cymbal", "Guitar Fret Noise", "Breath Noise", "Seashore", "Bird Tweet", "Telephone Ring", "Helicopter", "Applause", "Gunshot" }));
        controleInstrumento.setToolTipText("");
        controleInstrumento.setBorder(null);
        PainelConfiguracoes.add(controleInstrumento);
        controleInstrumento.setBounds(446, 260, 530, 110);

        fundoConfiguracoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fundoConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/configuracoes.png"))); // NOI18N
        PainelConfiguracoes.add(fundoConfiguracoes);
        fundoConfiguracoes.setBounds(0, 0, 1024, 768);

        botaoConfiguracoesVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfiguracoesVoltarActionPerformed(evt);
            }
        });
        PainelConfiguracoes.add(botaoConfiguracoesVoltar);
        botaoConfiguracoesVoltar.setBounds(40, 650, 130, 90);

        PainelPrincipal.add(PainelConfiguracoes, "cartaoConfiguracoes");

        PainelTocador.setLayout(null);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textoTocador.setColumns(20);
        textoTocador.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        textoTocador.setLineWrap(true);
        textoTocador.setRows(5);
        textoTocador.setBorder(null);
        jScrollPane3.setViewportView(textoTocador);

        PainelTocador.add(jScrollPane3);
        jScrollPane3.setBounds(30, 30, 960, 460);

        nomeArquivo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        nomeArquivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PainelTocador.add(nomeArquivo);
        nomeArquivo.setBounds(170, 530, 740, 50);

        fundoTocador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaplay.png"))); // NOI18N
        PainelTocador.add(fundoTocador);
        fundoTocador.setBounds(0, 0, 1024, 768);

        botaoTocadorVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTocadorVoltarActionPerformed(evt);
            }
        });
        PainelTocador.add(botaoTocadorVoltar);
        botaoTocadorVoltar.setBounds(20, 520, 120, 80);
        PainelTocador.add(botaoTocadorSalvar);
        botaoTocadorSalvar.setBounds(920, 520, 70, 80);
        PainelTocador.add(botaoTocadorStop);
        botaoTocadorStop.setBounds(150, 630, 130, 130);
        PainelTocador.add(botaoTocadorPause);
        botaoTocadorPause.setBounds(440, 630, 140, 130);

        botaoTocadorPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTocadorPlayActionPerformed(evt);
            }
        });
        PainelTocador.add(botaoTocadorPlay);
        botaoTocadorPlay.setBounds(740, 630, 130, 130);

        PainelPrincipal.add(PainelTocador, "cartaoTocador");

        PainelEdicao.setLayout(null);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textoEdicao.setColumns(20);
        textoEdicao.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        textoEdicao.setLineWrap(true);
        textoEdicao.setRows(5);
        textoEdicao.setBorder(null);
        textoEdicao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textoEdicao.setHighlighter(null);
        jScrollPane1.setViewportView(textoEdicao);

        PainelEdicao.add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 970, 570);

        fundoEdicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaedicao.png"))); // NOI18N
        PainelEdicao.add(fundoEdicao);
        fundoEdicao.setBounds(0, 0, 1024, 768);

        botaoEdicaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEdicaoVoltarActionPerformed(evt);
            }
        });
        PainelEdicao.add(botaoEdicaoVoltar);
        botaoEdicaoVoltar.setBounds(40, 660, 130, 70);

        botaoEdicaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEdicaoSalvarActionPerformed(evt);
            }
        });
        PainelEdicao.add(botaoEdicaoSalvar);
        botaoEdicaoSalvar.setBounds(390, 660, 80, 70);

        PainelPrincipal.add(PainelEdicao, "cartaoEdicao");

        PainelAjuda.setLayout(null);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textoAjuda.setEditable(false);
        textoAjuda.setColumns(20);
        textoAjuda.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        textoAjuda.setLineWrap(true);
        textoAjuda.setRows(5);
        textoAjuda.setBorder(null);
        jScrollPane2.setViewportView(textoAjuda);

        PainelAjuda.add(jScrollPane2);
        jScrollPane2.setBounds(30, 20, 970, 570);

        EasterEgg.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        EasterEgg.setForeground(new java.awt.Color(255, 255, 153));
        EasterEgg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EasterEgg.setText("MIM");
        PainelAjuda.add(EasterEgg);
        EasterEgg.setBounds(560, 650, 190, 80);

        fundoAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaajuda.png"))); // NOI18N
        PainelAjuda.add(fundoAjuda);
        fundoAjuda.setBounds(0, 0, 1024, 768);

        botaoAjudaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAjudaVoltarActionPerformed(evt);
            }
        });
        PainelAjuda.add(botaoAjudaVoltar);
        botaoAjudaVoltar.setBounds(40, 660, 130, 70);

        botaoEasterEgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEasterEggActionPerformed(evt);
            }
        });
        PainelAjuda.add(botaoEasterEgg);
        botaoEasterEgg.setBounds(83, 620, 40, 9);

        PainelPrincipal.add(PainelAjuda, "cartaoAjuda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInicialAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicialAvancarActionPerformed
        if (textoEdicao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione uma entrada!");
        } 
        else{
            novaMusica = new Musica(textoEdicao.getText());
            textoTocador.setText(novaMusica.pegaNotas());
            CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
            cartao.show(PainelPrincipal, "cartaoTocador");
        }
    }//GEN-LAST:event_botaoInicialAvancarActionPerformed

    private void botaoInicialAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicialAjudaActionPerformed
        String ajudatxt = LeitorArquivo.leArquivo("ajuda.txt");
        textoAjuda.setText(ajudatxt);
        textoAjuda.setCaretPosition(0);  // colocar scroll no topo
        EasterEgg.setVisible(false);  
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoAjuda");
    }//GEN-LAST:event_botaoInicialAjudaActionPerformed

    private void botaoInicialConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicialConfiguracoesActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoConfiguracoes");
    }//GEN-LAST:event_botaoInicialConfiguracoesActionPerformed

    private void botaoConfiguracoesVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfiguracoesVoltarActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoInicial");
    }//GEN-LAST:event_botaoConfiguracoesVoltarActionPerformed

    private void botaoTocadorVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTocadorVoltarActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoInicial");
    }//GEN-LAST:event_botaoTocadorVoltarActionPerformed

    private void botaoEdicaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEdicaoVoltarActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoInicial");
    }//GEN-LAST:event_botaoEdicaoVoltarActionPerformed

    private void botaoAjudaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAjudaVoltarActionPerformed
        CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
        cartao.show(PainelPrincipal, "cartaoInicial");
    }//GEN-LAST:event_botaoAjudaVoltarActionPerformed

    private void botaoInicialEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicialEntradaActionPerformed
        Object[] opcoesTexto = { "Arquivo", "Texto" };
        Integer opcaoEntrada = JOptionPane.showOptionDialog(this,"Selecione o modo de entrada:","Entrada",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opcoesTexto,opcoesTexto[0]);
        if (opcaoEntrada == 0){ // escolher a primeira opçao, ou seja "Arquivo"
            JFileChooser seletorArquivo = new JFileChooser();
            int foiSelecionado = seletorArquivo.showOpenDialog(this);
            if(foiSelecionado == JFileChooser.APPROVE_OPTION){
                File arquivoEntrada = seletorArquivo.getSelectedFile();
                String caminhoArquivo = arquivoEntrada.getAbsolutePath();
                nomeArquivo.setText(arquivoEntrada.getName());

                String entradaLida = LeitorArquivo.leArquivo(caminhoArquivo);
                textoEdicao.setText(entradaLida);
                textoEdicao.setCaretPosition(0);
                CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
                cartao.show(PainelPrincipal, "cartaoEdicao");
            }
        }
            
        else if (opcaoEntrada == 1){ // escolher a segunda opcao, ou seja "Texto"
            textoEdicao.setText("");
            textoEdicao.setCaretPosition(0);
            CardLayout cartao = (CardLayout) PainelPrincipal.getLayout();
            cartao.show(PainelPrincipal, "cartaoEdicao");
        }
       
    }//GEN-LAST:event_botaoInicialEntradaActionPerformed

    private void botaoEasterEggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEasterEggActionPerformed
         EasterEgg.setVisible(true);
    }//GEN-LAST:event_botaoEasterEggActionPerformed

    private void botaoEdicaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEdicaoSalvarActionPerformed
        
    }//GEN-LAST:event_botaoEdicaoSalvarActionPerformed

    private void botaoTocadorPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTocadorPlayActionPerformed
        try {
            novaMusica.tocaMusica();
        } catch (InvalidMidiDataException ex) {
            Logger.getLogger(TelaInterface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MidiUnavailableException ex) {
            Logger.getLogger(TelaInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoTocadorPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
               
               //javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EasterEgg;
    private javax.swing.JPanel PainelAjuda;
    private javax.swing.JPanel PainelConfiguracoes;
    private javax.swing.JPanel PainelEdicao;
    private javax.swing.JPanel PainelInicial;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainelTocador;
    private javax.swing.JButton botaoAjudaVoltar;
    private javax.swing.JButton botaoConfiguracoesVoltar;
    private javax.swing.JButton botaoEasterEgg;
    private javax.swing.JButton botaoEdicaoSalvar;
    private javax.swing.JButton botaoEdicaoVoltar;
    private javax.swing.JButton botaoInicialAjuda;
    private javax.swing.JButton botaoInicialAvancar;
    private javax.swing.JButton botaoInicialConfiguracoes;
    private javax.swing.JButton botaoInicialEntrada;
    private javax.swing.JButton botaoTocadorPause;
    private javax.swing.JButton botaoTocadorPlay;
    private javax.swing.JButton botaoTocadorSalvar;
    private javax.swing.JButton botaoTocadorStop;
    private javax.swing.JButton botaoTocadorVoltar;
    private javax.swing.JComboBox<String> controleInstrumento;
    private javax.swing.JSlider controleVolume;
    private javax.swing.JLabel fundoAjuda;
    private javax.swing.JLabel fundoConfiguracoes;
    private javax.swing.JLabel fundoEdicao;
    private javax.swing.JLabel fundoInicial;
    private javax.swing.JLabel fundoTocador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nomeArquivo;
    private javax.swing.JTextArea textoAjuda;
    private javax.swing.JTextArea textoEdicao;
    private javax.swing.JTextArea textoTocador;
    // End of variables declaration//GEN-END:variables
}
